#!/usr/bin/env bash 
# This script loops from 1 to 10 and displays:
# "bad luck" for the 4th iteration,
# "good luck" for the 8th iteration,
# "Best School" for all other iterations.


i=1

while [ "$i" -lt 10 ]; do

   if [ $i -eq 4 ]; then

       echo "bad luck"

   elif [ $i -q 8 ]; then

       echo "good luck"

   else 

       echo "Best School"
 
   fi

i=$((i + 1))

done
