#!/usr/bin/env bash
#This scripts diplays "bad luck" on 4th iteration, "good luck" on 8th iteretion and "Best School" for other iterations

i=1

while [ "$i" -le 10 ]; do

   if [ $i -eq 4 ]; then

       echo "bad luck"

   elif [ $i -q 8 ]; then

       echo "good luck"

   else 

       echo "Best School"
 
   fi

i=$((i + 1))

done
