#!/usr/bib/env bash
# This script check if the school file exists, whether it is empty, and if it's a regular file


if [ -e "school" ]; then

    echo "school file exists"

    # Check if the file is not empty

    if [ ! -s "school" ]; then

    echo "school file is empty"	    
    
    else 

    echo "school file is not empty"

    fi

    # check if it's a regular file

if [ -f "school" ]; then 

   echo "school is a regular file"
   
   fi

   else 

echo "school file does not exist"

fi
