#!/usr/bin/env bash
# This script displays all currently running processes for all users, including those without a TTY, in a hierarchical format.
ps -e -o user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command --forest
